/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

public class App {
    private final List<String> input;

    public App(List<String> input) {
        this.input = input;
    }

    public Integer getSolutionPart1() {
        int sum = 0;
        int elf = 0;
        int total = 0;
        int i = 1;
        for(String n : input) {
            if(!n.isEmpty()) {
                int in=Integer.parseInt(n);
                total = in + total;
            } else {
                if(total > sum) {
                    elf = i;
                    sum = total;
                }
                i++;
                total = 0;
            }
        };
        return sum;
    }

    public Integer getSolutionPart2() {
        int sum1 = 0;
        int sum2 = 0;
        int sum3 = 0;

        int total = 0;

        for(String n : input) {
            if(!n.isEmpty()) {
                int in=Integer.parseInt(n);
                total = in + total;
            } else {

                if(total > sum1) {
                    sum3 = sum2;
                    sum2 = sum1;
                    sum1 = total;
                }
                else if(total > sum2) {
                    sum3 = sum2;
                    sum2 = total;
                }
                else if(total > sum3) {
                    sum3 = total;
                }
                total = 0;
            }
        };

        if(total > sum1) {
            sum3 = sum2;
            sum2 = sum1;
            sum1 = total;
        }
        else if(total > sum2) {
            sum3 = sum2;
            sum2 = total;
        }
        else if(total > sum3) {
            sum3 = total;
        }

        return sum1+sum2+sum3;
    }

    public static void main(String[] args) throws IOException {
        System.out.println("java");
        List<String> input = parseInput("input.txt");
        String part = System.getenv("part") == null ? "part1" : System.getenv("part");
        if (part.equals("part2"))
            System.out.println(new App(input).getSolutionPart2());
        else
            System.out.println(new App(input).getSolutionPart1());
    }

    private static List<String> parseInput(String filename) throws IOException {
        return Files.lines(Path.of(filename))
                .collect(Collectors.toList());
    }
}
