/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

public class App {

    public App() {
    }

    public Integer getSolution(String input, Integer no) {
        List<Character> ch = input.chars()
                .mapToObj(e->(char)e).toList();

        for (int i = no; i < ch.size(); i++) {
            List<Character> sublist = ch.subList(i - no, i);
            Set<Character> targetSet = new HashSet<>(sublist);
            if(targetSet.size() == no) {
                return i;
            }
        }
        return 0;
    }

    public Integer getSolutionPart1(String input) {
        return getSolution(input, 4);
    }

    public Integer getSolutionPart2(String input) {
        return getSolution(input, 14);
    }


    public static void main(String[] args) throws IOException {
        List<String> input = parseInput("input.txt");
        String part = System.getenv("part") == null ? "part1" : System.getenv("part");
        if (part.equals("part2"))
            System.out.println(new App().getSolutionPart2(input.get(0)));
        else
            System.out.println(new App().getSolutionPart1(input.get(0)));
    }

    private static List<String> parseInput(String filename) throws IOException {
        return Files.lines(Path.of(filename))
                .collect(Collectors.toList());
    }
}
