/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

public class App {
    private final List<String> input;
    private Map<String, Integer> pointsTable = new HashMap<String, Integer>() {
        {
            put("X", 0);
            put("Y", 1);
            put("Z", 2);
            put("A", 0);
            put("B", 1);
            put("C", 2);
        }
    };
    private Map<String, Integer> opponentMove;

    public App(List<String> input) {
        this.input = input;

    }

    public Integer getSolutionPart1() {
        int points = 0;
        for(String move : input) {
            int p = 0;
            String[] moves = move.split(" ");
            p = p + pointsTable.get(moves[1]) + 1;
            int winner = (3 + pointsTable.get(moves[1]) - pointsTable.get(moves[0])) % 3;
            if(winner == 1) {
                p = p + 6;
            } else if (winner == 0) {
                p = p + 3;
            }
            points = points + p;
        }
        return points;
    }

    public Integer getSolutionPart2() {
        int points = 0;
        for(String move : input) {
            int p = 0;
            String[] moves = move.split(" ");

            if(moves[1].equals("X")) {
                // I need to lose
                if(moves[0].equals("A")) {
                    p=p+3;
                } else if (moves[0].equals("B")) {
                    p=p+1;
                } else {
                    p=p+2;
                }
            } else if (moves[1].equals("Y")) {
                // this needs a draw
                p = p + 3;
                p = p + pointsTable.get(moves[0]) + 1;
            } else {
                // I need to win
                if(moves[0].equals("A")) {
                    p=p+2;
                } else if (moves[0].equals("B")) {
                    p=p+3;
                } else {
                    p=p+1;
                }
                p = p + 6;
            }
            points = points + p;
        }
        return points;
    }

    public static void main(String[] args) throws IOException {
        List<String> input = parseInput("input.txt");
        String part = System.getenv("part") == null ? "part1" : System.getenv("part");
        if (part.equals("part2"))
            System.out.println(new App(input).getSolutionPart2());
        else
            System.out.println(new App(input).getSolutionPart1());
    }

    private static List<String> parseInput(String filename) throws IOException {
        return Files.lines(Path.of(filename))
                .collect(Collectors.toList());
    }
}
