/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    App classUnderTest;
    App app;

    @BeforeEach
    void createSubject() throws IOException {

        classUnderTest = new App();

        app = new App();
    }

    @Test
    void part1Solution() {
        assertEquals(7, classUnderTest.getSolutionPart1("mjqjpqmgbljsphdztnvjfqwrcgsmlb"));
        assertEquals(5, classUnderTest.getSolutionPart1("bvwbjplbgvbhsrlpgdmjqwftvncz"));
        assertEquals(6, classUnderTest.getSolutionPart1("nppdvjthqldpwncqszvftbrmjlhg"));
        assertEquals(10, classUnderTest.getSolutionPart1("nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg"));
        assertEquals(11, classUnderTest.getSolutionPart1("zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw"));
    }

    @Test
    void part2Solution() {
        assertEquals(19, classUnderTest.getSolutionPart2("mjqjpqmgbljsphdztnvjfqwrcgsmlb"));
        assertEquals(23, classUnderTest.getSolutionPart2("bvwbjplbgvbhsrlpgdmjqwftvncz"));
        assertEquals(23, classUnderTest.getSolutionPart2("nppdvjthqldpwncqszvftbrmjlhg"));
        assertEquals(29, classUnderTest.getSolutionPart2("nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg"));
        assertEquals(26, classUnderTest.getSolutionPart2("zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw"));
    }


    private static List<String> parseInput(String filename) throws IOException {
        return Files.lines(Path.of(filename))
                .collect(Collectors.toList());
    }
}
