/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    App classUnderTest;
    @BeforeEach
    void createSubject() throws IOException {
        List<String> input = parseInput("input_test.txt");
        classUnderTest = new App(input);
    }

    @Test void part1SumsInput() {
        assertEquals(24000, classUnderTest.getSolutionPart1());
    }
    @Test void part2SumsInput() {
        assertEquals(45000, classUnderTest.getSolutionPart2());
    }

    private static List<String> parseInput(String filename) throws IOException {
        return Files.lines(Path.of(filename))
                .collect(Collectors.toList());
    }
}
